"use client";

import { useMemo, useState } from "react";
import { Beaker, Calculator, ChevronRight, Construction, Droplets, Layers3, Ruler, Waves } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";

type CalculatorKey="volume"|"water"|"substrate";
const field="mt-1.5 w-full rounded-xl border border-white/[.08] bg-[#09171e] px-3 py-3 text-sm font-bold outline-none focus:border-aqua/60";
const sandTypes=[
 {id:"silica",name:"Silis kum",density:1.55,note:"İnce ve doğal görünümlü"},{id:"basalt",name:"Bazalt kum",density:1.7,note:"Koyu renkli ve ağır"},{id:"aquasoil",name:"Aquasoil",density:.85,note:"Bitkili akvaryum toprağı"},{id:"coral",name:"Mercan kırığı",density:1.25,note:"Sertliği yükseltebilir"},{id:"gravel",name:"Doğal çakıl",density:1.6,note:"Orta ve iri taneli"},
];

export default function CalculatorsPage(){const [active,setActive]=useState<CalculatorKey>("volume");return <AppShell><PageHeader title="Hesaplayıcılar"/><div className="mx-auto max-w-[1100px] px-5 py-8 sm:px-8 lg:px-10 lg:py-10"><div className="mb-8"><p className="eyebrow mb-2 text-aqua">Araç kutusu</p><h1 className="text-2xl font-extrabold sm:text-3xl">Hesaplayıcılar</h1><p className="mt-2 text-sm text-[#71858d]">Akvaryum kurulumunda tahminleri net rakamlara dönüştür.</p></div><div className="mb-5 grid gap-3 sm:grid-cols-3"><ToolButton icon={Ruler} title="Akvaryum hacmi" description="Brüt ve tahmini net litre" selected={active==="volume"} onClick={()=>setActive("volume")}/><ToolButton icon={Droplets} title="Su değişimi" description="Yüzde ve litre hesabı" selected={active==="water"} onClick={()=>setActive("water")}/><ToolButton icon={Layers3} title="Kum hesabı" description="Litre ve yaklaşık ağırlık" selected={active==="substrate"} onClick={()=>setActive("substrate")}/></div>{active==="volume"?<VolumeCalculator/>:active==="water"?<WaterChangeCalculator/>:<SubstrateCalculator/>}<ComingSoon/></div></AppShell>}

function ToolButton({icon:Icon,title,description,selected,onClick}:{icon:typeof Ruler;title:string;description:string;selected:boolean;onClick:()=>void}){return <button onClick={onClick} className={`surface flex items-center gap-4 p-4 text-left transition ${selected?"border-aqua/30 bg-aqua/[.06]":"hover:border-white/15"}`}><span className={`grid size-11 shrink-0 place-items-center rounded-xl ${selected?"bg-aqua text-ink":"bg-white/[.04] text-[#71858d]"}`}><Icon size={20}/></span><div><p className={`text-sm font-extrabold ${selected?"text-aqua":""}`}>{title}</p><p className="mt-1 text-[9px] text-[#647981]">{description}</p></div><ChevronRight size={15} className="ml-auto text-[#40545d]"/></button>}

function VolumeCalculator(){const [size,setSize]=useState({length:100,width:45,height:50});const [loss,setLoss]=useState(15);const gross=size.length*size.width*size.height/1000;const net=gross*(1-loss/100);return <CalculatorPanel icon={Ruler} eyebrow="Hacim" title="Akvaryum hacim hesaplayıcı" help="İç cam ölçülerini santimetre olarak gir."><div className="grid grid-cols-3 gap-3">{(["length","width","height"] as const).map((key,i)=><NumberField key={key} label={["Uzunluk","Genişlik","Yükseklik"][i]} value={size[key]} unit="cm" onChange={v=>setSize({...size,[key]:v})}/>)}</div><div className="mt-4"><NumberField label="Dekor, kum ve boşluk payı" value={loss} unit="%" min={0} max={50} onChange={setLoss}/></div><ResultGrid results={[{label:"Brüt hacim",value:gross.toFixed(1),unit:"litre",accent:true},{label:"Tahmini net hacim",value:net.toFixed(1),unit:"litre"},{label:"Taban alanı",value:((size.length*size.width)/10000).toFixed(2),unit:"m²"}]}/></CalculatorPanel>}

function WaterChangeCalculator(){const [volume,setVolume]=useState(180);const [percent,setPercent]=useState(30);const amount=volume*percent/100;return <CalculatorPanel icon={Droplets} eyebrow="Bakım" title="Su değişimi hesaplayıcı" help="Akvaryum net hacmini ve değiştirmek istediğin oranı gir."><div className="grid gap-3 sm:grid-cols-2"><NumberField label="Net akvaryum hacmi" value={volume} unit="L" onChange={setVolume}/><NumberField label="Değişim oranı" value={percent} unit="%" min={1} max={100} onChange={setPercent}/></div><ResultGrid results={[{label:"Değiştirilecek su",value:amount.toFixed(1),unit:"litre",accent:true},{label:"Akvaryumda kalan",value:(volume-amount).toFixed(1),unit:"litre"},{label:"Yaklaşık 10 L kova",value:Math.ceil(amount/10).toString(),unit:"kova"}]}/><div className="mt-4 rounded-xl border border-amber-300/10 bg-amber-300/[.05] p-4 text-[10px] leading-relaxed text-amber-200/70">Yeni suyun sıcaklık ve kimyasal değerlerini akvaryum suyuna yakın tutmayı unutma.</div></CalculatorPanel>}

function SubstrateCalculator(){const [size,setSize]=useState({length:100,width:45,front:4,back:7});const [sandId,setSandId]=useState("aquasoil");const sand=sandTypes.find(s=>s.id===sandId)!;const average=(size.front+size.back)/2;const liters=size.length*size.width*average/1000;const kilograms=liters*sand.density;return <CalculatorPanel icon={Layers3} eyebrow="Taban" title="Kum litre hesaplayıcı" help="Eğimli taban için ön ve arka kum yüksekliğini ayrı girebilirsin."><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><NumberField label="Uzunluk" value={size.length} unit="cm" onChange={v=>setSize({...size,length:v})}/><NumberField label="Genişlik" value={size.width} unit="cm" onChange={v=>setSize({...size,width:v})}/><NumberField label="Ön yükseklik" value={size.front} unit="cm" onChange={v=>setSize({...size,front:v})}/><NumberField label="Arka yükseklik" value={size.back} unit="cm" onChange={v=>setSize({...size,back:v})}/></div><label className="mt-4 block text-[10px] font-bold text-[#91a3aa]">Kum türü<select value={sandId} onChange={e=>setSandId(e.target.value)} className={field}>{sandTypes.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="mt-3 rounded-xl bg-white/[.025] p-3 text-[10px] text-[#71858d]">{sand.note} · Yaklaşık yoğunluk: {sand.density} kg/L</div><ResultGrid results={[{label:"Gerekli kum",value:liters.toFixed(1),unit:"litre",accent:true},{label:"Yaklaşık ağırlık",value:kilograms.toFixed(1),unit:"kg"},{label:"Ortalama kalınlık",value:average.toFixed(1),unit:"cm"}]}/><p className="mt-4 text-[9px] leading-relaxed text-[#586e77]">Ağırlık değeri tane boyutu, nem ve üreticiye göre değişebilir. Satın alırken %5–10 pay bırakılması önerilir.</p></CalculatorPanel>}

function CalculatorPanel({icon:Icon,eyebrow,title,help,children}:{icon:typeof Calculator;eyebrow:string;title:string;help:string;children:React.ReactNode}){return <section className="surface p-5 sm:p-7"><div className="mb-7 flex items-start gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-aqua/10 text-aqua"><Icon size={21}/></span><div><p className="eyebrow text-aqua">{eyebrow}</p><h2 className="mt-1 text-lg font-extrabold">{title}</h2><p className="mt-1 text-[10px] text-[#647981]">{help}</p></div></div>{children}</section>}
function NumberField({label,value,unit,onChange,min=0,max}:{label:string;value:number;unit:string;onChange:(v:number)=>void;min?:number;max?:number}){return <label className="text-[10px] font-bold text-[#91a3aa]">{label}<div className="relative"><input type="number" min={min} max={max} step="any" value={value} onChange={e=>onChange(Number(e.target.value))} className={`${field} pr-10`}/><span className="absolute right-3 top-[19px] text-[9px] text-[#586e77]">{unit}</span></div></label>}
function ResultGrid({results}:{results:Array<{label:string;value:string;unit:string;accent?:boolean}>}){return <div className="mt-6 grid gap-3 sm:grid-cols-3">{results.map(r=><div key={r.label} className={`rounded-xl border p-4 ${r.accent?"border-aqua/20 bg-aqua/[.07]":"border-white/[.06] bg-white/[.02]"}`}><p className={`text-[9px] font-bold uppercase tracking-wider ${r.accent?"text-aqua/70":"text-[#586e77]"}`}>{r.label}</p><p className={`mt-2 text-2xl font-extrabold ${r.accent?"text-aqua":""}`}>{r.value} <span className="text-[10px] text-[#71858d]">{r.unit}</span></p></div>)}</div>}
function ComingSoon(){return <section className="mt-5"><div className="mb-3 flex items-center gap-2"><Construction size={15} className="text-[#647981]"/><p className="eyebrow">Yakında</p></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-5">{[[Beaker,"CO₂"],[Waves,"GH / KH"],[Droplets,"Gübre"],[Layers3,"Mineral / Tuz"],[Calculator,"TDS"]].map(([Icon,label])=>{const ToolIcon=Icon as typeof Beaker;return <div key={String(label)} className="surface flex items-center gap-3 p-3 opacity-55"><ToolIcon size={16} className="text-[#71858d]"/><span className="text-[10px] font-bold">{String(label)}</span></div>})}</div></section>}
