"use client";

import { AlertTriangle, ArrowLeft, CheckCircle2, ChevronRight, CircleGauge, Droplets, Fish, Heater, ShieldAlert, Waves } from "lucide-react";
import { useParams } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import { analyzeAquarium } from "@/lib/health-analysis";
import { useAquariums } from "@/providers/aquarium-provider";

const tones={good:{text:"text-emerald-400",bg:"bg-emerald-400",soft:"bg-emerald-400/10",label:"İyi"},warning:{text:"text-amber-300",bg:"bg-amber-300",soft:"bg-amber-300/10",label:"Dikkat"},danger:{text:"text-red-400",bg:"bg-red-400",soft:"bg-red-400/10",label:"Yüksek risk"}};

export default function HealthPage(){
 const {id}=useParams<{id:string}>(); const {aquariums,hydrated,livestock,equipment,waterReadings}=useAquariums(); const aquarium=aquariums.find(a=>a.id===id);
 if(!hydrated)return <AppShell><PageHeader title="Sağlık Analizi"/><div className="grid min-h-[60vh] place-items-center text-sm text-[#71858d]">Analiz hazırlanıyor…</div></AppShell>;
 if(!aquarium)return <AppShell><PageHeader title="Sağlık Analizi"/><div className="p-16 text-center">Akvaryum bulunamadı.</div></AppShell>;
 const animals=livestock.filter(i=>i.aquariumId===id); const devices=equipment.filter(i=>i.aquariumId===id); const latest=waterReadings.filter(i=>i.aquariumId===id).sort((a,b)=>+new Date(b.measuredAt)-+new Date(a.measuredAt))[0]; const analysis=analyzeAquarium(aquarium,animals,devices,latest); const overall=tones[analysis.status];
 return <AppShell><PageHeader title="Sağlık Analizi"/><div className="mx-auto max-w-[1180px] px-5 py-8 sm:px-8 lg:px-10 lg:py-10"><a href={`/aquariums/${id}`} className="mb-6 inline-flex items-center gap-2 text-xs font-bold text-[#82969e]"><ArrowLeft size={15}/>{aquarium.name}</a><div className="mb-7"><p className="eyebrow mb-2 text-aqua">Uyumluluk ve biyolojik yük</p><h1 className="text-2xl font-extrabold sm:text-3xl">Sağlık Analizi</h1><p className="mt-2 text-sm text-[#71858d]">Akvaryum, canlı, ekipman ve son ölçümlerin birlikte değerlendirildi.</p></div>
  <div className="grid gap-5 lg:grid-cols-[.75fr_1.5fr]"><section className="surface grid place-items-center p-7 text-center"><ScoreRing score={analysis.score} status={analysis.status}/><p className={`mt-5 rounded-full px-3 py-1.5 text-[10px] font-extrabold uppercase ${overall.soft} ${overall.text}`}>{overall.label}</p><p className="mt-3 text-[10px] leading-relaxed text-[#647981]">Bu skor bir tanı değil, kayıtlı bilgilere dayalı açıklanabilir bir rehberdir.</p></section><section className="surface p-5 sm:p-6"><div className="mb-5"><p className="eyebrow">Alt başlıklar</p><h2 className="mt-1 text-lg font-extrabold">Uygunluk göstergeleri</h2></div><div className="space-y-5">{analysis.metrics.map(({key,...metric})=><MetricBar key={key} {...metric}/>)}</div></section></div>
  <section className="surface mt-5 overflow-hidden"><div className="border-b border-white/[.06] p-5 sm:p-6"><p className="eyebrow">Öneriler</p><h2 className="mt-1 text-lg font-extrabold">Dikkat edilmesi gerekenler</h2></div>{analysis.warnings.length?<div className="divide-y divide-white/[.05]">{analysis.warnings.map((warning,index)=><div key={`${warning.title}-${index}`} className="flex gap-4 p-5"><span className={`grid size-10 shrink-0 place-items-center rounded-xl ${warning.level==="danger"?"bg-red-400/10 text-red-400":"bg-amber-300/10 text-amber-300"}`}>{warning.level==="danger"?<ShieldAlert size={19}/>:<AlertTriangle size={19}/>}</span><div><p className="text-sm font-extrabold">{warning.title}</p><p className="mt-1 text-[10px] leading-relaxed text-[#71858d]">{warning.message}</p></div></div>)}</div>:<div className="flex items-center gap-4 p-6"><span className="grid size-10 place-items-center rounded-xl bg-emerald-400/10 text-emerald-400"><CheckCircle2 size={19}/></span><div><p className="text-sm font-extrabold">Belirgin bir risk görünmüyor</p><p className="mt-1 text-[10px] text-[#71858d]">Düzenli ölçüm ve bakım kayıtlarına devam et.</p></div></div>}</section>
  <div className="mt-5 grid gap-3 sm:grid-cols-3"><DataLink href={`/livestock?aquarium=${id}`} icon={Fish} title="Canlıları güncelle" detail={`${animals.length} tür kayıtlı`}/><DataLink href={`/equipment?aquarium=${id}`} icon={Heater} title="Ekipmanı güncelle" detail={`${devices.length} ekipman kayıtlı`}/><DataLink href={`/water?aquarium=${id}`} icon={Droplets} title="Su ölçümü ekle" detail={latest?"Son ölçüm analize dahil":"Ölçüm bekleniyor"}/></div>
 </div></AppShell>
}

function ScoreRing({score,status}:{score:number;status:keyof typeof tones}){const color=status==="good"?"#34d399":status==="warning"?"#fbbf24":"#f87171";return <div className="relative size-44"><svg viewBox="0 0 120 120" className="size-full -rotate-90"><circle cx="60" cy="60" r="50" fill="none" stroke="rgba(255,255,255,.06)" strokeWidth="9"/><circle cx="60" cy="60" r="50" fill="none" stroke={color} strokeWidth="9" strokeLinecap="round" strokeDasharray={`${score*3.14} 314`}/></svg><div className="absolute inset-0 grid place-items-center"><div><p className="text-4xl font-extrabold">{score}</p><p className="text-[9px] font-bold uppercase tracking-wider text-[#647981]">100 üzerinden</p></div></div></div>}
function MetricBar({label,score,status,detail}:{label:string;score:number;status:keyof typeof tones;detail:string}){const tone=tones[status];return <div><div className="mb-2 flex items-end justify-between"><div><p className="text-xs font-bold">{label}</p><p className="mt-1 text-[9px] text-[#647981]">{detail}</p></div><span className={`text-sm font-extrabold ${tone.text}`}>{score}%</span></div><div className="h-2 overflow-hidden rounded-full bg-white/[.05]"><div className={`h-full rounded-full ${tone.bg}`} style={{width:`${score}%`}}/></div></div>}
function DataLink({href,icon:Icon,title,detail}:{href:string;icon:typeof Waves;title:string;detail:string}){return <a href={href} className="surface flex items-center gap-3 p-4 hover:border-aqua/20"><span className="grid size-10 place-items-center rounded-xl bg-aqua/10 text-aqua"><Icon size={18}/></span><div><p className="text-xs font-bold">{title}</p><p className="mt-1 text-[9px] text-[#647981]">{detail}</p></div><ChevronRight size={14} className="ml-auto text-[#586e77]"/></a>}
