"use client";

import { FormEvent, Suspense, useMemo, useState } from "react";
import { CalendarCheck, Check, ChevronDown, Clock3, Plus, Repeat2, Sparkles, X } from "lucide-react";
import { useSearchParams } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import { useAquariums } from "@/providers/aquarium-provider";
import type { MaintenanceTask, MaintenanceType } from "@/types/aquarium";

const types: Array<[MaintenanceType,string]>=[["water_change","Su değişimi"],["glass_cleaning","Cam temizliği"],["filter_cleaning","Filtre temizliği"],["filter_media_change","Filtre malzemesi değişimi"],["trimming","Budama"],["fertilizing","Gübreleme"],["co2_refill","CO₂ tüpü değişimi"],["medication","İlaç uygulaması"],["note","Genel not"]];
const field="mt-1.5 w-full rounded-xl border border-white/[.08] bg-[#09171e] px-3 py-3 text-sm outline-none focus:border-aqua/60";

export default function MaintenancePage(){return <Suspense fallback={<AppShell><PageHeader title="Bakım Günlüğü"/></AppShell>}><Content/></Suspense>}

function Content(){
  const search=useSearchParams(); const {aquariums,maintenanceTasks,addMaintenanceTask,completeMaintenanceTask}=useAquariums();
  const requested=search.get("aquarium"); const [aquariumId,setAquariumId]=useState(requested&&aquariums.some(a=>a.id===requested)?requested:aquariums[0]?.id??"");
  const [filter,setFilter]=useState<"upcoming"|"completed"|"all">("upcoming"); const [open,setOpen]=useState(false);
  const all=maintenanceTasks.filter(t=>t.aquariumId===aquariumId); const upcoming=all.filter(t=>!t.completedAt); const completed=all.filter(t=>t.completedAt);
  const tasks=useMemo(()=>all.filter(t=>filter==="all"||(filter==="completed"?!!t.completedAt:!t.completedAt)).sort((a,b)=>+new Date(a.dueAt)-+new Date(b.dueAt)),[all,filter]);
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);const type=d.get("type") as MaintenanceType;addMaintenanceTask({id:crypto.randomUUID(),aquariumId,type,title:String(d.get("title")||types.find(x=>x[0]===type)?.[1]),dueAt:new Date(String(d.get("dueAt"))).toISOString(),recurrenceDays:Number(d.get("recurrenceDays"))||undefined,amountPercent:Number(d.get("amountPercent"))||undefined,amountLiters:Number(d.get("amountLiters"))||undefined,notes:String(d.get("notes")||"")});setOpen(false)}
  return <AppShell><PageHeader title="Bakım Günlüğü"/><div className="mx-auto max-w-[1200px] px-5 py-8 sm:px-8 lg:px-10 lg:py-10">
    <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow mb-2 text-aqua">Rutinler</p><h1 className="text-2xl font-extrabold sm:text-3xl">Bakım Günlüğü</h1><p className="mt-2 text-sm text-[#71858d]">Akvaryum bakımını düzenli ve kayıtlı tut.</p></div><div className="flex gap-2"><label className="relative flex-1 sm:min-w-52"><select value={aquariumId} onChange={e=>setAquariumId(e.target.value)} className="w-full appearance-none rounded-xl border border-white/[.08] bg-panel px-4 py-3 pr-9 text-xs font-bold outline-none">{aquariums.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><ChevronDown size={14} className="pointer-events-none absolute right-3 top-3.5 text-[#71858d]"/></label><button onClick={()=>setOpen(true)} className="flex items-center gap-2 rounded-xl bg-aqua px-4 py-3 text-xs font-extrabold text-ink"><Plus size={16}/>Bakım ekle</button></div></div>
    <div className="mb-5 grid grid-cols-3 gap-3"><Stat icon={Clock3} label="Yaklaşan" value={upcoming.length} tone="text-amber-300 bg-amber-300/10"/><Stat icon={Check} label="Tamamlanan" value={completed.length} tone="text-emerald-400 bg-emerald-400/10"/><Stat icon={Repeat2} label="Tekrarlayan" value={upcoming.filter(t=>t.recurrenceDays).length} tone="text-aqua bg-aqua/10"/></div>
    <section className="surface overflow-hidden"><div className="flex flex-col justify-between gap-4 border-b border-white/[.06] p-5 sm:flex-row sm:items-center sm:p-6"><div><p className="eyebrow">Plan</p><h2 className="mt-1 text-lg font-extrabold">Bakım kayıtları</h2></div><div className="flex rounded-xl bg-white/[.03] p-1">{(["upcoming","completed","all"] as const).map(k=><button key={k} onClick={()=>setFilter(k)} className={`rounded-lg px-3 py-2 text-[10px] font-bold ${filter===k?"bg-aqua/10 text-aqua":"text-[#647981]"}`}>{k==="upcoming"?"Yaklaşan":k==="completed"?"Tamamlanan":"Tümü"}</button>)}</div></div>
      <div className="divide-y divide-white/[.045]">{tasks.map(t=><TaskRow key={t.id} task={t} done={()=>completeMaintenanceTask(t.id)}/>)}{!tasks.length&&<div className="grid min-h-56 place-items-center text-center"><div><CalendarCheck size={34} className="mx-auto mb-3 text-aqua"/><p className="text-sm font-bold">Bakım kaydı yok</p><p className="mt-1 text-xs text-[#647981]">Yeni bir görev ekleyerek planını oluştur.</p></div></div>}</div>
    </section>
  </div>{open&&<MaintenanceForm aquariumName={aquariums.find(a=>a.id===aquariumId)?.name??""} close={()=>setOpen(false)} submit={submit}/>}</AppShell>
}

function Stat({icon:Icon,label,value,tone}:{icon:typeof Clock3;label:string;value:number;tone:string}){return <div className="surface p-4 sm:p-5"><span className={`mb-4 grid size-9 place-items-center rounded-lg ${tone}`}><Icon size={17}/></span><p className="text-2xl font-extrabold">{value}</p><p className="mt-1 text-[9px] font-bold uppercase tracking-wider text-[#647981]">{label}</p></div>}
function TaskRow({task,done}:{task:MaintenanceTask;done:()=>void}){return <div className={`flex items-center gap-4 p-4 sm:p-5 ${task.completedAt?"opacity-55":""}`}><button onClick={done} disabled={!!task.completedAt} className={`grid size-10 shrink-0 place-items-center rounded-xl border ${task.completedAt?"border-emerald-400/20 bg-emerald-400/10 text-emerald-400":"border-white/10 text-[#586e77] hover:text-aqua"}`}><Check size={17}/></button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className={`text-sm font-bold ${task.completedAt?"line-through":""}`}>{task.title}</p>{task.recurrenceDays&&<span className="rounded-full bg-aqua/10 px-2 py-1 text-[8px] font-bold text-aqua">Her {task.recurrenceDays} gün</span>}</div><p className="mt-1 text-[10px] text-[#647981]">{types.find(x=>x[0]===task.type)?.[1]}{task.amountPercent?` · %${task.amountPercent}`:""}{task.amountLiters?` · ${task.amountLiters} L`:""}</p></div><div className="shrink-0 text-right"><p className="text-xs font-bold">{new Date(task.completedAt??task.dueAt).toLocaleDateString("tr-TR",{day:"numeric",month:"short"})}</p><p className="mt-1 text-[9px] text-[#647981]">{task.completedAt?"Tamamlandı":"Planlandı"}</p></div></div>}
function MaintenanceForm({aquariumName,close,submit}:{aquariumName:string;close:()=>void;submit:(e:FormEvent<HTMLFormElement>)=>void}){const [type,setType]=useState<MaintenanceType>("water_change");return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 backdrop-blur-sm sm:items-center sm:p-5"><form onSubmit={submit} className="max-h-[92vh] w-full max-w-xl overflow-y-auto rounded-t-2xl border border-white/[.08] bg-panel p-5 sm:rounded-2xl sm:p-7"><div className="mb-6 flex justify-between"><div><p className="eyebrow text-aqua">{aquariumName}</p><h2 className="mt-1 text-xl font-extrabold">Yeni bakım kaydı</h2></div><button type="button" onClick={close} className="grid size-9 place-items-center rounded-xl bg-white/[.04] text-[#71858d]"><X size={17}/></button></div><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-[#91a3aa]">Bakım türü<select name="type" value={type} onChange={e=>setType(e.target.value as MaintenanceType)} className={field}>{types.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label className="text-xs font-bold text-[#91a3aa]">Tarih ve saat<input required name="dueAt" type="datetime-local" defaultValue={new Date(Date.now()+86400000-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16)} className={field}/></label><label className="text-xs font-bold text-[#91a3aa] sm:col-span-2">Başlık<input name="title" placeholder={types.find(x=>x[0]===type)?.[1]} className={field}/></label>{type==="water_change"&&<><label className="text-xs font-bold text-[#91a3aa]">Değişim yüzdesi<input name="amountPercent" type="number" min="1" max="100" placeholder="30" className={field}/></label><label className="text-xs font-bold text-[#91a3aa]">Litre miktarı<input name="amountLiters" type="number" min="1" placeholder="50" className={field}/></label></>}<label className="text-xs font-bold text-[#91a3aa]">Tekrarlama (gün)<input name="recurrenceDays" type="number" min="1" placeholder="7" className={field}/></label><label className="text-xs font-bold text-[#91a3aa] sm:col-span-2">Notlar<textarea name="notes" rows={3} className={field}/></label></div><div className="mt-7 flex justify-end gap-2"><button type="button" onClick={close} className="rounded-xl border border-white/[.08] px-5 py-3 text-xs font-bold text-[#91a3aa]">Vazgeç</button><button className="flex items-center gap-2 rounded-xl bg-aqua px-5 py-3 text-xs font-extrabold text-ink"><Sparkles size={16}/>Kaydet</button></div></form></div>}
