"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { ChevronDown, ImagePlus, Leaf, MapPin, Plus, Search, Sprout, Trash2, X } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import { useAquariums } from "@/providers/aquarium-provider";
import type { Plant } from "@/types/aquarium";

const positions=["Ön plan","Orta plan","Arka plan","Kök üzeri","Kaya üzeri","Yüzen","Diğer"];
const field="mt-1.5 w-full rounded-xl border border-white/[.08] bg-[#09171e] px-3 py-3 text-sm outline-none focus:border-aqua/60";

export default function PlantsPage(){
 const {aquariums,plants,addPlant,removePlant}=useAquariums(); const [aquariumId,setAquariumId]=useState(aquariums[0]?.id??""); const [position,setPosition]=useState("Tümü"); const [query,setQuery]=useState(""); const [open,setOpen]=useState(false);
 useEffect(()=>{const requested=new URLSearchParams(location.search).get("aquarium");if(requested&&aquariums.some(a=>a.id===requested))setAquariumId(requested)},[aquariums]);
 const base=plants.filter(p=>p.aquariumId===aquariumId); const items=useMemo(()=>base.filter(p=>position==="Tümü"||p.position===position).filter(p=>(p.name+" "+(p.scientificName??"")).toLowerCase().includes(query.toLowerCase())),[base,position,query]);
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);addPlant({id:crypto.randomUUID(),aquariumId,name:String(d.get("name")),scientificName:String(d.get("scientificName")||""),quantity:Number(d.get("quantity")),position:String(d.get("position")||""),addedAt:String(d.get("addedAt")),notes:String(d.get("notes")||"")});setOpen(false)}
 return <AppShell><PageHeader title="Bitkiler"/><div className="mx-auto max-w-[1200px] px-5 py-8 sm:px-8 lg:px-10 lg:py-10">
  <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow mb-2 text-emerald-400">Flora</p><h1 className="text-2xl font-extrabold sm:text-3xl">Bitkiler</h1><p className="mt-2 text-sm text-[#71858d]">Bitki koleksiyonunu ve yerleşimini yönet.</p></div><div className="flex gap-2"><label className="relative flex-1 sm:min-w-52"><select value={aquariumId} onChange={e=>setAquariumId(e.target.value)} className="w-full appearance-none rounded-xl border border-white/[.08] bg-panel px-4 py-3 pr-9 text-xs font-bold outline-none">{aquariums.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><ChevronDown size={14} className="pointer-events-none absolute right-3 top-3.5 text-[#71858d]"/></label><button onClick={()=>setOpen(true)} className="flex items-center gap-2 rounded-xl bg-aqua px-4 py-3 text-xs font-extrabold text-ink"><Plus size={16}/>Bitki ekle</button></div></div>
  <div className="mb-5 grid grid-cols-3 gap-3"><Summary icon={Leaf} label="Bitki türü" value={base.length}/><Summary icon={Sprout} label="Toplam adet" value={base.reduce((s,p)=>s+p.quantity,0)}/><Summary icon={MapPin} label="Yerleşim alanı" value={new Set(base.map(p=>p.position).filter(Boolean)).size}/></div>
  <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:justify-between"><div className="flex gap-1 overflow-x-auto">{["Tümü",...positions].map(p=><button key={p} onClick={()=>setPosition(p)} className={`shrink-0 rounded-xl px-3 py-2.5 text-[10px] font-bold ${position===p?"bg-emerald-400/10 text-emerald-400":"bg-white/[.025] text-[#647981]"}`}>{p}</button>)}</div><label className="relative"><Search size={15} className="absolute left-3 top-3 text-[#586e77]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Bitki ara..." className="w-full rounded-xl border border-white/[.07] bg-panel py-2.5 pl-9 pr-3 text-xs outline-none sm:w-52"/></label></div>
  {items.length?<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map(plant=><article key={plant.id} className="surface overflow-hidden"><div className="relative grid h-36 place-items-center bg-gradient-to-br from-[#103528] via-[#0c2c26] to-[#0b2022]"><span className="grid size-16 place-items-center rounded-full bg-emerald-400/10 text-emerald-400"><Leaf size={31}/></span>{plant.position&&<span className="absolute right-3 top-3 rounded-full bg-black/25 px-2 py-1 text-[8px] font-bold">{plant.position}</span>}</div><div className="p-4"><div className="flex justify-between gap-3"><div><h2 className="text-sm font-extrabold">{plant.name}</h2><p className="mt-1 text-[10px] italic text-[#647981]">{plant.scientificName||"Bilimsel ad eklenmemiş"}</p></div><span className="text-xl font-extrabold text-emerald-400">{plant.quantity}</span></div><div className="mt-4 flex items-center justify-between border-t border-white/[.05] pt-3"><p className="text-[9px] text-[#586e77]">Eklendi: {new Date(plant.addedAt).toLocaleDateString("tr-TR")}</p><button onClick={()=>confirm(`${plant.name} silinsin mi?`)&&removePlant(plant.id)} className="text-[#586e77] hover:text-red-400"><Trash2 size={14}/></button></div></div></article>)}</div>:<Empty/>}
 </div>{open&&<PlantForm aquariumName={aquariums.find(a=>a.id===aquariumId)?.name??""} close={()=>setOpen(false)} submit={submit}/>}</AppShell>
}
function Summary({icon:Icon,label,value}:{icon:typeof Leaf;label:string;value:number}){return <div className="surface p-4"><Icon size={17} className="mb-4 text-emerald-400"/><p className="text-2xl font-extrabold">{value}</p><p className="mt-1 text-[9px] font-bold uppercase tracking-wider text-[#647981]">{label}</p></div>}
function Empty(){return <div className="surface grid min-h-64 place-items-center text-center"><div><Leaf size={38} className="mx-auto mb-3 text-emerald-400"/><p className="text-sm font-bold">Bitki bulunamadı</p><p className="mt-1 text-xs text-[#647981]">İlk bitki kaydını ekleyebilirsin.</p></div></div>}
function PlantForm({aquariumName,close,submit}:{aquariumName:string;close:()=>void;submit:(e:FormEvent<HTMLFormElement>)=>void}){return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 backdrop-blur-sm sm:items-center sm:p-5"><form onSubmit={submit} className="max-h-[92vh] w-full max-w-xl overflow-y-auto rounded-t-2xl border border-white/[.08] bg-panel p-5 sm:rounded-2xl sm:p-7"><div className="mb-6 flex justify-between"><div><p className="eyebrow text-emerald-400">{aquariumName}</p><h2 className="mt-1 text-xl font-extrabold">Yeni bitki ekle</h2></div><button type="button" onClick={close} className="grid size-9 place-items-center rounded-xl bg-white/[.04] text-[#71858d]"><X size={17}/></button></div><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-[#91a3aa]">Bitki adı<input required name="name" placeholder="Örn. Anubias Nana" className={field}/></label><label className="text-xs font-bold text-[#91a3aa]">Bilimsel adı<input name="scientificName" placeholder="Anubias barteri var. nana" className={field}/></label><label className="text-xs font-bold text-[#91a3aa]">Adet<input required name="quantity" type="number" min="1" defaultValue="1" className={field}/></label><label className="text-xs font-bold text-[#91a3aa]">Konum<select name="position" className={field}>{positions.map(p=><option key={p}>{p}</option>)}</select></label><label className="text-xs font-bold text-[#91a3aa]">Eklenme tarihi<input required name="addedAt" type="date" defaultValue={new Date().toISOString().slice(0,10)} className={field}/></label><label className="text-xs font-bold text-[#91a3aa] sm:col-span-2">Notlar<textarea name="notes" rows={3} className={field}/></label><div className="flex items-center gap-3 rounded-xl border border-dashed border-white/10 p-4 text-[#647981] sm:col-span-2"><ImagePlus size={19}/><p className="text-[10px]">Fotoğraf yükleme bulut depolama aşamasında açılacak.</p></div></div><div className="mt-7 flex justify-end gap-2"><button type="button" onClick={close} className="rounded-xl border border-white/[.08] px-5 py-3 text-xs font-bold text-[#91a3aa]">Vazgeç</button><button className="rounded-xl bg-aqua px-5 py-3 text-xs font-extrabold text-ink">Bitkiyi kaydet</button></div></form></div>}
