"use client";

import { useEffect, useState } from "react";
import { Bell, Check, Database, Download, Globe2, Moon, Ruler, ShieldCheck, Trash2, UserRound } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";

interface Preferences { temperature:"celsius"|"fahrenheit"; volume:"liters"|"gallons"; dateFormat:"day-first"|"month-first"; maintenance:boolean; waterAlerts:boolean; productNews:boolean; compactMode:boolean; }
const defaults:Preferences={temperature:"celsius",volume:"liters",dateFormat:"day-first",maintenance:true,waterAlerts:true,productNews:false,compactMode:false};
const input="mt-1.5 w-full rounded-xl border border-white/[.08] bg-[#09171e] px-3 py-3 text-sm outline-none focus:border-aqua/60";

export default function SettingsPage(){
 const [prefs,setPrefs]=useState(defaults); const [saved,setSaved]=useState(false);
 useEffect(()=>{try{const data=localStorage.getItem("aquamind:preferences:v1");if(data)setPrefs(JSON.parse(data))}catch{}},[]);
 function save(){localStorage.setItem("aquamind:preferences:v1",JSON.stringify(prefs));setSaved(true);setTimeout(()=>setSaved(false),1800)}
 function exportData(){const data:Record<string,unknown>={exportedAt:new Date().toISOString(),version:1};for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key?.startsWith("aquamind:")){try{data[key]=JSON.parse(localStorage.getItem(key)??"null")}catch{data[key]=localStorage.getItem(key)}}}const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`aquamind-yedek-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)}
 function reset(){if(!confirm("Tüm yerel AquaMind verileri silinsin mi? Bu işlem geri alınamaz."))return;Object.keys(localStorage).filter(k=>k.startsWith("aquamind:")).forEach(k=>localStorage.removeItem(k));location.reload()}
 return <AppShell><PageHeader title="Ayarlar"/><div className="mx-auto max-w-[980px] px-5 py-8 sm:px-8 lg:px-10 lg:py-10"><div className="mb-8"><p className="eyebrow mb-2 text-aqua">Tercihler</p><h1 className="text-2xl font-extrabold sm:text-3xl">Ayarlar</h1><p className="mt-2 text-sm text-[#71858d]">AquaMind deneyimini ihtiyaçlarına göre düzenle.</p></div>
  <div className="space-y-5"><Section icon={UserRound} title="Profil" description="Uygulamada görünen profil bilgilerin"><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-[#91a3aa]">Ad soyad<input defaultValue="Mert Kaya" className={input}/></label><label className="text-xs font-bold text-[#91a3aa]">E-posta<input type="email" placeholder="ornek@email.com" className={input}/></label></div><p className="mt-3 text-[9px] text-[#586e77]">Gerçek kullanıcı hesabı eklendiğinde bu bilgiler hesabınla eşitlenecek.</p></Section>
  <Section icon={Ruler} title="Birimler ve bölge" description="Hesaplamalarda kullanılacak ölçü biçimleri"><div className="grid gap-4 sm:grid-cols-3"><Select label="Sıcaklık" value={prefs.temperature} onChange={v=>setPrefs({...prefs,temperature:v as Preferences["temperature"]})} options={[["celsius","Santigrat (°C)"],["fahrenheit","Fahrenheit (°F)"]]}/><Select label="Hacim" value={prefs.volume} onChange={v=>setPrefs({...prefs,volume:v as Preferences["volume"]})} options={[["liters","Litre (L)"],["gallons","Galon (US)"]]}/><Select label="Tarih biçimi" value={prefs.dateFormat} onChange={v=>setPrefs({...prefs,dateFormat:v as Preferences["dateFormat"]})} options={[["day-first","GG.AA.YYYY"],["month-first","AA/GG/YYYY"]]}/></div></Section>
  <Section icon={Bell} title="Bildirimler" description="Hatırlatma ve bilgilendirme tercihleri"><div className="divide-y divide-white/[.05]"><Toggle label="Bakım hatırlatmaları" description="Yaklaşan bakım görevlerinde hatırlat" checked={prefs.maintenance} onChange={v=>setPrefs({...prefs,maintenance:v})}/><Toggle label="Su değeri uyarıları" description="Değerler güvenli aralığın dışına çıktığında bildir" checked={prefs.waterAlerts} onChange={v=>setPrefs({...prefs,waterAlerts:v})}/><Toggle label="Ürün haberleri" description="Yeni özellikler hakkında bilgi ver" checked={prefs.productNews} onChange={v=>setPrefs({...prefs,productNews:v})}/></div></Section>
  <Section icon={Moon} title="Görünüm" description="Arayüz ve yoğunluk seçenekleri"><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-aqua/20 bg-aqua/[.05] p-4"><div className="flex items-center justify-between"><div><p className="text-xs font-bold">Koyu tema</p><p className="mt-1 text-[9px] text-[#647981]">AquaMind varsayılanı</p></div><Check size={17} className="text-aqua"/></div></div><Toggle label="Kompakt görünüm" description="Kartlarda daha fazla bilgi göster" checked={prefs.compactMode} onChange={v=>setPrefs({...prefs,compactMode:v})}/></div></Section>
  <Section icon={Database} title="Veri yönetimi" description="Yerel kayıtlarını yedekle veya temizle"><div className="grid gap-3 sm:grid-cols-2"><button onClick={exportData} className="flex items-center gap-3 rounded-xl border border-white/[.07] p-4 text-left hover:border-aqua/25"><span className="grid size-9 place-items-center rounded-lg bg-aqua/10 text-aqua"><Download size={17}/></span><div><p className="text-xs font-bold">Verileri dışa aktar</p><p className="mt-1 text-[9px] text-[#647981]">JSON yedeği indir</p></div></button><button onClick={reset} className="flex items-center gap-3 rounded-xl border border-red-400/10 p-4 text-left hover:border-red-400/30"><span className="grid size-9 place-items-center rounded-lg bg-red-400/10 text-red-400"><Trash2 size={17}/></span><div><p className="text-xs font-bold text-red-300">Tüm verileri sıfırla</p><p className="mt-1 text-[9px] text-[#647981]">Cihazdaki kayıtları sil</p></div></button></div></Section>
  <div className="flex flex-col items-center justify-between gap-3 rounded-2xl border border-white/[.06] bg-white/[.02] p-4 sm:flex-row"><div className="flex items-center gap-3"><ShieldCheck size={18} className="text-emerald-400"/><div><p className="text-xs font-bold">Verilerin bu cihazda saklanıyor</p><p className="mt-1 text-[9px] text-[#647981]">Bulut senkronizasyonu hesap sistemiyle eklenecek.</p></div></div><button onClick={save} className="flex w-full items-center justify-center gap-2 rounded-xl bg-aqua px-5 py-3 text-xs font-extrabold text-ink sm:w-auto">{saved?<><Check size={16}/>Kaydedildi</>:"Ayarları kaydet"}</button></div>
  <div className="flex items-center justify-center gap-2 py-3 text-[9px] text-[#40545d]"><Globe2 size={12}/>AquaMind MVP · Türkçe · v0.1</div></div></div></AppShell>
}

function Section({icon:Icon,title,description,children}:{icon:typeof UserRound;title:string;description:string;children:React.ReactNode}){return <section className="surface p-5 sm:p-6"><div className="mb-5 flex items-start gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-lg bg-aqua/10 text-aqua"><Icon size={17}/></span><div><h2 className="text-sm font-extrabold">{title}</h2><p className="mt-1 text-[9px] text-[#647981]">{description}</p></div></div>{children}</section>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:string[][]}){return <label className="text-xs font-bold text-[#91a3aa]">{label}<select value={value} onChange={e=>onChange(e.target.value)} className={input}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function Toggle({label,description,checked,onChange}:{label:string;description:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="flex cursor-pointer items-center justify-between gap-4 py-4 first:pt-0 last:pb-0"><div><p className="text-xs font-bold">{label}</p><p className="mt-1 text-[9px] text-[#647981]">{description}</p></div><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="sr-only"/><span className={`relative h-6 w-11 shrink-0 rounded-full transition ${checked?"bg-aqua":"bg-white/10"}`}><span className={`absolute top-1 size-4 rounded-full bg-white transition ${checked?"left-6":"left-1"}`}/></span></label>}
